### ISSUE TITLE
Document workaround of removing app data folder and reinstalling

### ISSUE THREAD

**Issue by ristomatti** [httptoolkit/httptoolkit-website#62]
Ref: https://github.com/httptoolkit/httptoolkit/issues/481

**Comment by pimterry** [comment]
Thanks for the suggestion. Unfortunately though this isn't a general solution to most issues - just to this failed updates specifically, and half the time it won't work anyway (if the update is still live, it'll just update again and bring the error back) - and it has some notable downsides (it removes all updates and all app state, so there's lots of potential for data loss) so overall I'm not super keen to add it as an official troubleshooting suggestion.

This is also notably a rare error case that shouldn't generally happen - unless a bad update was live just now while you were last using the app, you'll never see this issue.

And of course, in general, bad updates shouldn't go live like this in the first place! I'm looking into the testing at the moment to see why this didn't get caught, but in general I'd expect this to be a very rare occurrence. 

For now I'm going to close this. I think it's better for specific error cases like this to be handled via GitHub, with discussions and solutions there appropriate for the specific problem. 

I'll add a few notes to help with that now, like adding 'check GitHub issues' to the troubleshooting docs & contact form. Any more suggestions to help make GitHub issues for active bugs like this visible are very welcome! Bit tricky to do in-app since it doesn't actually start in the extreme failure case like this, but I think there might be options there.
